User.create(name: "denny", password: "cat")
Question.create(question: "What is muh name?")
Answer.create(answer: "tek 9")
Picture.create(picture_url: 'public/pictures/Cat.jpg')
Quap.create(question_id: 1, answer_id: 1, picture_id: 1, user_id: 1)
